/* Dear Days service worker */
const VERSION = 'dd-v32';
const CORE = ["./", "index.html", "manifest.webmanifest", "css/app.css", "js/data.js", "js/icons.js", "js/core.js", "js/render.js", "js/editor.js", "js/inspector.js", "js/panels.js", "js/theme.js", "js/export.js", "js/app.js", "icons/icon-192.png", "icons/icon-512.png", "textures/thumbs/fur-matchagreen.webp", "textures/thumbs/fur-strawberry.webp", "textures/thumbs/gingham-black.webp", "textures/thumbs/gingham-green.webp", "textures/thumbs/gingham-pink.webp", "textures/thumbs/gingham-red.webp", "textures/thumbs/glossy-babyblue.webp", "textures/thumbs/glossy-babypink.webp", "textures/thumbs/glossy-black.webp", "textures/thumbs/glossy-coffee.webp", "textures/thumbs/glossy-cyan.webp", "textures/thumbs/glossy-darkbrown.webp", "textures/thumbs/glossy-gray.webp", "textures/thumbs/glossy-green.webp", "textures/thumbs/glossy-hotpink.webp", "textures/thumbs/glossy-lavender.webp", "textures/thumbs/glossy-navy.webp", "textures/thumbs/glossy-neongreen.webp", "textures/thumbs/glossy-offwhite.webp", "textures/thumbs/glossy-pastelgreen.webp", "textures/thumbs/glossy-red.webp", "textures/thumbs/glossy-strawberry.webp", "textures/thumbs/glossy-strawberrymilk.webp", "textures/thumbs/glossy-winered.webp", "textures/thumbs/glossy-yellow.webp", "textures/thumbs/hardcover-babyblue.webp", "textures/thumbs/hardcover-babypink.webp", "textures/thumbs/hardcover-beige.webp", "textures/thumbs/hardcover-black.webp", "textures/thumbs/hardcover-cyan.webp", "textures/thumbs/hardcover-darkbrown.webp", "textures/thumbs/hardcover-gray.webp", "textures/thumbs/hardcover-green.webp", "textures/thumbs/hardcover-hotpink.webp", "textures/thumbs/hardcover-lavender.webp", "textures/thumbs/hardcover-navy.webp", "textures/thumbs/hardcover-neongreen.webp", "textures/thumbs/hardcover-offwhite.webp", "textures/thumbs/hardcover-red.webp", "textures/thumbs/hardcover-winered.webp", "textures/thumbs/hardcover-yellow.webp", "textures/thumbs/plushie-babyblue.webp", "textures/thumbs/plushie-babypink.webp", "textures/thumbs/plushie-black.webp", "textures/thumbs/plushie-coffee.webp", "textures/thumbs/plushie-cyan.webp", "textures/thumbs/plushie-darkbrown.webp", "textures/thumbs/plushie-gray.webp", "textures/thumbs/plushie-green.webp", "textures/thumbs/plushie-hotpink.webp", "textures/thumbs/plushie-lavender.webp", "textures/thumbs/plushie-matchagreen.webp", "textures/thumbs/plushie-navy.webp", "textures/thumbs/plushie-neongreen.webp", "textures/thumbs/plushie-offwhite.webp", "textures/thumbs/plushie-pastelgreen.webp", "textures/thumbs/plushie-red.webp", "textures/thumbs/plushie-strawberry.webp", "textures/thumbs/plushie-winered.webp", "textures/thumbs/plushie-yellow.webp"];
const TEXTURES = ["textures/fur-matchagreen.webp", "textures/fur-strawberry.webp", "textures/gingham-black.webp", "textures/gingham-green.webp", "textures/gingham-pink.webp", "textures/gingham-red.webp", "textures/glossy-babyblue.webp", "textures/glossy-babypink.webp", "textures/glossy-black.webp", "textures/glossy-coffee.webp", "textures/glossy-cyan.webp", "textures/glossy-darkbrown.webp", "textures/glossy-gray.webp", "textures/glossy-green.webp", "textures/glossy-hotpink.webp", "textures/glossy-lavender.webp", "textures/glossy-navy.webp", "textures/glossy-neongreen.webp", "textures/glossy-offwhite.webp", "textures/glossy-pastelgreen.webp", "textures/glossy-red.webp", "textures/glossy-strawberry.webp", "textures/glossy-strawberrymilk.webp", "textures/glossy-winered.webp", "textures/glossy-yellow.webp", "textures/hardcover-babyblue.webp", "textures/hardcover-babypink.webp", "textures/hardcover-beige.webp", "textures/hardcover-black.webp", "textures/hardcover-cyan.webp", "textures/hardcover-darkbrown.webp", "textures/hardcover-gray.webp", "textures/hardcover-green.webp", "textures/hardcover-hotpink.webp", "textures/hardcover-lavender.webp", "textures/hardcover-navy.webp", "textures/hardcover-neongreen.webp", "textures/hardcover-offwhite.webp", "textures/hardcover-red.webp", "textures/hardcover-winered.webp", "textures/hardcover-yellow.webp", "textures/plushie-babyblue.webp", "textures/plushie-babypink.webp", "textures/plushie-black.webp", "textures/plushie-coffee.webp", "textures/plushie-cyan.webp", "textures/plushie-darkbrown.webp", "textures/plushie-gray.webp", "textures/plushie-green.webp", "textures/plushie-hotpink.webp", "textures/plushie-lavender.webp", "textures/plushie-matchagreen.webp", "textures/plushie-navy.webp", "textures/plushie-neongreen.webp", "textures/plushie-offwhite.webp", "textures/plushie-pastelgreen.webp", "textures/plushie-red.webp", "textures/plushie-strawberry.webp", "textures/plushie-winered.webp", "textures/plushie-yellow.webp", "ribbons/babyblue.webp", "ribbons/babypink.webp", "ribbons/black.webp", "ribbons/cyan.webp", "ribbons/darkbrown.webp", "ribbons/emeraldgreen.webp", "ribbons/gray.webp", "ribbons/hotpink.webp", "ribbons/lavender.webp", "ribbons/matchagreen.webp", "ribbons/navy.webp", "ribbons/offwhite.webp", "ribbons/orange.webp", "ribbons/purple.webp", "ribbons/red.webp", "ribbons/winered.webp", "ribbons/yellow.webp"];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(async c => {
    await c.addAll(CORE);
    // textures are cached in the background so install stays quick
    c.addAll(TEXTURES).catch(() => {});
  }));
  self.skipWaiting();
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== VERSION && k !== 'dd-fonts').map(k => caches.delete(k)))));
  self.clients.claim();
});
self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;
  if (url.origin === location.origin) {
    // app files: network first so updates arrive, cache as fallback; textures: cache first
    if (url.pathname.includes('/textures/') || url.pathname.includes('/ribbons/')) {
      e.respondWith(caches.match(e.request).then(r => r || fetch(e.request).then(res => { const cp = res.clone(); caches.open(VERSION).then(c => c.put(e.request, cp)); return res; })));
    } else {
      e.respondWith(fetch(e.request).then(res => { const cp = res.clone(); caches.open(VERSION).then(c => c.put(e.request, cp)); return res; }).catch(() => caches.match(e.request, { ignoreSearch: true })));
    }
    return;
  }
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open('dd-fonts').then(c => c.match(e.request).then(r => r || fetch(e.request).then(res => { c.put(e.request, res.clone()); return res; }))));
  }
});
